from fastapi import FastAPI, Request                                                                                                                                                                          
from fastapi.responses import FileResponse, JSONResponse                                                                                                                                                       
from fastapi.staticfiles import StaticFiles                                                                                                                                                                    
from fastapi.middleware.cors import CORSMiddleware                                                                                                                                                             
from pydantic import BaseModel                                                                                                                                                                                 
import google.generativeai as genai                                                                                                                                                                            
from dotenv import load_dotenv                                                                                                                                                                                 
import os                                                                                                                                                                                                      
                                                                                                                                                                                                               
load_dotenv()                                                                                                                                                                                                  
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))                                                                                                                                                           
model = genai.GenerativeModel(model_name="models/gemini-1.5-pro-latest")                                                                                                                                       
app = FastAPI()                                                                                                                                                                                                

# Allow frontend JS to call backend                                                                                                                                                                            
app.add_middleware(                                                                                                                                                                                            
    CORSMiddleware,                                                                                                                                                                                            
    allow_origins=["*"],  # Or ["http://localhost:8000"] for strict                                                                                                                                            
    allow_credentials=True,                                                                                                                                                                                        allow_methods=["*"],                                                                                                                                                                                      
    allow_headers=["*"],                                                                                                                                                                                       
)                                                                                                                                                                                                                                                                                                                                                                                                                             
# Serve static files like index.html                                                                                                                                                                           
app.mount("/static", StaticFiles(directory="static"), name="static")
@app.get("/")                                                                                                                                                                                                  
def get_index():                                                                                                                                                                                               
    return FileResponse("static/index.html")                                                                                                                                                                                                                                                                                                                                                                                  
# Your AI API route                                                                                                                                                                                            
class Prompt(BaseModel):                                                                                                                                                                                       
    text: str                                                                                                                                                                                                                                                                                                                                                                                                                 
@app.post("/generate")                                                                                                                                                                                         
async def generate_text(prompt: Prompt):                                                                                                                                                                       
    try:                                                                                                                                                                                                       
        response = model.generate_content(prompt.text)                                                                                                                                                         
        return {"response": response.text}                                                                                                                                                                     
    except Exception as e:                                                                                                                                                                                     
        return JSONResponse(                                                                                                                                                                                           status_code=500,                                                                                                                                                                                               content={"error": str(e)}                                                                                                                                                                           
        )                                                                                                                                                                                                      
#models = genai.list_models()                                                                                                                                                                                  
#for m in models:                                                                                                                                                                                              
#   print(m.name)  
